services:
  backend:
    build:
      context: ../management-employees-company  
      dockerfile: Dockerfile                    
    container_name: gestion_empleados_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_H2_CONSOLE_ENABLED=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .                       
      dockerfile: Dockerfile
    container_name: gestion_empleados_frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
