version: "3.8"
services:
  backend:
    build:
      context: ./management-employees-company/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_H2_CONSOLE_ENABLED=true
    networks:
      - app-network

  frontend:
    build:
      context: ./hiberus-company-emps-frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 